args <- commandArgs(trailingOnly = TRUE)
print(args)
source(args[[2]] + "blacklist.R")
source(args[[2]] + "init.R")
source(args[[2]] + "masked.functions.R")
source(args[[2]] + "sandbox.R")
src <- readChar(args[[1]], file.info(args[[1]]$size))
sandbox(src)
